name: dev_workflow

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  terraform-init-plan:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 3a3d0f1a-3b27-4f4e-8bbb-0094cac4d8f2
          tenant-id: cb139084-0e90-46f4-9031-8067a8f29787
          subscription-id: 16648c27-24de-48bf-b2d6-cc829eea5412
         
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: environments/dev
           
      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: environments/dev
  
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: environments/dev
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: environments/dev
        
  terraform-apply:
    runs-on: self-hosted
    needs: terraform-init-plan
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 3a3d0f1a-3b27-4f4e-8bbb-0094cac4d8f2
          tenant-id: cb139084-0e90-46f4-9031-8067a8f29787
          subscription-id: 16648c27-24de-48bf-b2d6-cc829eea5412
    
      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: environments/dev

      - name: Terraform apply
        id: apply
        run: terraform apply --auto-approve
        continue-on-error: true
        working-directory: environments/dev
          
