name: "testing_workflow"

on: workflow_dispatch

permissions:
  id-token: write
  contents: read
  
jobs: 
  terraform-job:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
      
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: af8c3a34-e56a-4033-a815-ff9f0a08b779
        tenant-id: cb139084-0e90-46f4-9031-8067a8f29787
        subscription-id: 16648c27-24de-48bf-b2d6-cc829eea5412
            
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
      working-directory: environments/dev
    
    - name: Terraform Init
      id: init
      run: terraform init -input=false
      working-directory: environments/dev
        
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: environments/dev
      
    
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      continue-on-error: true
      working-directory: environments/dev
    
